//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("RecipeOrganizerModel", "FK_Ingredients_Recipes", "Recipes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RecipeForDisaster.Recipe), "Ingredients", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RecipeForDisaster.Ingredient), true)]

#endregion

namespace RecipeForDisaster
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RecipeOrganizerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RecipeOrganizerEntities object using the connection string found in the 'RecipeOrganizerEntities' section of the application configuration file.
        /// </summary>
        public RecipeOrganizerEntities() : base("name=RecipeOrganizerEntities", "RecipeOrganizerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RecipeOrganizerEntities object.
        /// </summary>
        public RecipeOrganizerEntities(string connectionString) : base(connectionString, "RecipeOrganizerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RecipeOrganizerEntities object.
        /// </summary>
        public RecipeOrganizerEntities(EntityConnection connection) : base(connection, "RecipeOrganizerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ingredient> Ingredients
        {
            get
            {
                if ((_Ingredients == null))
                {
                    _Ingredients = base.CreateObjectSet<Ingredient>("Ingredients");
                }
                return _Ingredients;
            }
        }
        private ObjectSet<Ingredient> _Ingredients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Recipe> Recipes
        {
            get
            {
                if ((_Recipes == null))
                {
                    _Recipes = base.CreateObjectSet<Recipe>("Recipes");
                }
                return _Recipes;
            }
        }
        private ObjectSet<Recipe> _Recipes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ingredients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIngredients(Ingredient ingredient)
        {
            base.AddObject("Ingredients", ingredient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Recipes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecipes(Recipe recipe)
        {
            base.AddObject("Recipes", recipe);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RecipeOrganizerModel", Name="Ingredient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ingredient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ingredient object.
        /// </summary>
        /// <param name="ingredientID">Initial value of the IngredientID property.</param>
        /// <param name="ingredient1">Initial value of the Ingredient1 property.</param>
        /// <param name="recipeID">Initial value of the RecipeID property.</param>
        public static Ingredient CreateIngredient(global::System.Int32 ingredientID, global::System.String ingredient1, global::System.Int32 recipeID)
        {
            Ingredient ingredient = new Ingredient();
            ingredient.IngredientID = ingredientID;
            ingredient.Ingredient1 = ingredient1;
            ingredient.RecipeID = recipeID;
            return ingredient;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IngredientID
        {
            get
            {
                return _IngredientID;
            }
            set
            {
                if (_IngredientID != value)
                {
                    OnIngredientIDChanging(value);
                    ReportPropertyChanging("IngredientID");
                    _IngredientID = StructuralObject.SetValidValue(value, "IngredientID");
                    ReportPropertyChanged("IngredientID");
                    OnIngredientIDChanged();
                }
            }
        }
        private global::System.Int32 _IngredientID;
        partial void OnIngredientIDChanging(global::System.Int32 value);
        partial void OnIngredientIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ingredient1
        {
            get
            {
                return _Ingredient1;
            }
            set
            {
                OnIngredient1Changing(value);
                ReportPropertyChanging("Ingredient1");
                _Ingredient1 = StructuralObject.SetValidValue(value, false, "Ingredient1");
                ReportPropertyChanged("Ingredient1");
                OnIngredient1Changed();
            }
        }
        private global::System.String _Ingredient1;
        partial void OnIngredient1Changing(global::System.String value);
        partial void OnIngredient1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeID
        {
            get
            {
                return _RecipeID;
            }
            set
            {
                OnRecipeIDChanging(value);
                ReportPropertyChanging("RecipeID");
                _RecipeID = StructuralObject.SetValidValue(value, "RecipeID");
                ReportPropertyChanged("RecipeID");
                OnRecipeIDChanged();
            }
        }
        private global::System.Int32 _RecipeID;
        partial void OnRecipeIDChanging(global::System.Int32 value);
        partial void OnRecipeIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RecipeOrganizerModel", "FK_Ingredients_Recipes", "Recipes")]
        public Recipe Recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("RecipeOrganizerModel.FK_Ingredients_Recipes", "Recipes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("RecipeOrganizerModel.FK_Ingredients_Recipes", "Recipes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Recipe> RecipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("RecipeOrganizerModel.FK_Ingredients_Recipes", "Recipes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Recipe>("RecipeOrganizerModel.FK_Ingredients_Recipes", "Recipes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RecipeOrganizerModel", Name="Recipe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Recipe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Recipe object.
        /// </summary>
        /// <param name="recipeID">Initial value of the RecipeID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="directions">Initial value of the Directions property.</param>
        /// <param name="recipeType">Initial value of the RecipeType property.</param>
        public static Recipe CreateRecipe(global::System.Int32 recipeID, global::System.String title, global::System.String directions, global::System.String recipeType)
        {
            Recipe recipe = new Recipe();
            recipe.RecipeID = recipeID;
            recipe.Title = title;
            recipe.Directions = directions;
            recipe.RecipeType = recipeType;
            return recipe;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeID
        {
            get
            {
                return _RecipeID;
            }
            set
            {
                if (_RecipeID != value)
                {
                    OnRecipeIDChanging(value);
                    ReportPropertyChanging("RecipeID");
                    _RecipeID = StructuralObject.SetValidValue(value, "RecipeID");
                    ReportPropertyChanged("RecipeID");
                    OnRecipeIDChanged();
                }
            }
        }
        private global::System.Int32 _RecipeID;
        partial void OnRecipeIDChanging(global::System.Int32 value);
        partial void OnRecipeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Yield
        {
            get
            {
                return _Yield;
            }
            set
            {
                OnYieldChanging(value);
                ReportPropertyChanging("Yield");
                _Yield = StructuralObject.SetValidValue(value, true, "Yield");
                ReportPropertyChanged("Yield");
                OnYieldChanged();
            }
        }
        private global::System.String _Yield;
        partial void OnYieldChanging(global::System.String value);
        partial void OnYieldChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServingSize
        {
            get
            {
                return _ServingSize;
            }
            set
            {
                OnServingSizeChanging(value);
                ReportPropertyChanging("ServingSize");
                _ServingSize = StructuralObject.SetValidValue(value, true, "ServingSize");
                ReportPropertyChanged("ServingSize");
                OnServingSizeChanged();
            }
        }
        private global::System.String _ServingSize;
        partial void OnServingSizeChanging(global::System.String value);
        partial void OnServingSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Directions
        {
            get
            {
                return _Directions;
            }
            set
            {
                OnDirectionsChanging(value);
                ReportPropertyChanging("Directions");
                _Directions = StructuralObject.SetValidValue(value, false, "Directions");
                ReportPropertyChanged("Directions");
                OnDirectionsChanged();
            }
        }
        private global::System.String _Directions;
        partial void OnDirectionsChanging(global::System.String value);
        partial void OnDirectionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true, "Comment");
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RecipeType
        {
            get
            {
                return _RecipeType;
            }
            set
            {
                OnRecipeTypeChanging(value);
                ReportPropertyChanging("RecipeType");
                _RecipeType = StructuralObject.SetValidValue(value, false, "RecipeType");
                ReportPropertyChanged("RecipeType");
                OnRecipeTypeChanged();
            }
        }
        private global::System.String _RecipeType;
        partial void OnRecipeTypeChanging(global::System.String value);
        partial void OnRecipeTypeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RecipeOrganizerModel", "FK_Ingredients_Recipes", "Ingredients")]
        public EntityCollection<Ingredient> Ingredients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ingredient>("RecipeOrganizerModel.FK_Ingredients_Recipes", "Ingredients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ingredient>("RecipeOrganizerModel.FK_Ingredients_Recipes", "Ingredients", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
